#pragma once
#ifndef COLORS_H_
#define COLORS_H_

#include <windows.h>

#define WHITE           FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#define CYAN            FOREGROUND_GREEN | FOREGROUND_BLUE  | FOREGROUND_INTENSITY
#define MAGENTA         FOREGROUND_RED   | FOREGROUND_BLUE  | FOREGROUND_INTENSITY
#define YELLOW          FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define LIGHT_GRAY      FOREGROUND_RED   | FOREGROUND_GREEN | FOREGROUND_BLUE
#define RED             FOREGROUND_RED   | FOREGROUND_INTENSITY
#define GREEN           FOREGROUND_GREEN | FOREGROUND_INTENSITY
#define BLUE            FOREGROUND_BLUE  | FOREGROUND_INTENSITY
#define DARK_YELLOW     FOREGROUND_RED   | FOREGROUND_GREEN
#define PURPLE          FOREGROUND_RED   | FOREGROUND_BLUE
#define DARK_CYAN       FOREGROUND_GREEN | FOREGROUND_BLUE
#define DARK_GRAY       FOREGROUND_INTENSITY
#define DARK_GREEN      FOREGROUND_GREEN
#define DARK_BLUE       FOREGROUND_BLUE
#define DARK_RED        FOREGROUND_RED
#define BLACK           0

#define BG_WHITE        BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#define BG_CYAN         BACKGROUND_GREEN | BACKGROUND_BLUE  | BACKGROUND_INTENSITY
#define BG_MAGENTA      BACKGROUND_RED   | BACKGROUND_BLUE  | BACKGROUND_INTENSITY
#define BG_YELLOW       BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BG_LIGHT_GRAY   BACKGROUND_RED   | BACKGROUND_GREEN | BACKGROUND_BLUE
#define BG_RED          BACKGROUND_RED   | BACKGROUND_INTENSITY
#define BG_GREEN        BACKGROUND_GREEN | BACKGROUND_INTENSITY
#define BG_BLUE         BACKGROUND_BLUE  | BACKGROUND_INTENSITY
#define BG_DARK_YELLOW  BACKGROUND_RED   | BACKGROUND_GREEN
#define BG_PURPLE       BACKGROUND_RED   | BACKGROUND_BLUE
#define BG_DARK_CYAN    BACKGROUND_GREEN | BACKGROUND_BLUE
#define BG_DARK_GRAY    BACKGROUND_INTENSITY
#define BG_DARK_GREEN   BACKGROUND_GREEN
#define BG_DARK_BLUE    BACKGROUND_BLUE
#define BG_DARK_RED     BACKGROUND_RED
#define BG_BLACK        0

#define COLOR_AMOUNT 16

namespace wcolors
{
	WORD getColorAttribute(char foreground, char background = BG_BLACK);

	WORD addForeground(char foreground);

	WORD addBackground(char background);

	WORD getForegroundColor(CHAR_INFO charInfo);

	WORD getBackgroundColor(CHAR_INFO charInfo);
};

#endif
